### ISSUE TITLE
Remove WoolyPooly from mining pools

### ISSUE THREAD

**Issue by l33d4n** [grincc/hub#8]
Statement from Wooly:

> Attention to MWC and GRIN miners.
> Due to constant glitches with payouts, we decided to remove these coins from the pool.
> The deadline for mining these coins is October 31st. Please keep your wallets open and running to receive payments.
> After delisting, the payout process may take additional time.
> The era is gone.

**Comment by davidtavarez** [comment]
Thanks! Removed.
